name: example
description: edge_shelf example
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  supabase_functions: ^0.0.1
  edge_shelf:
    path: ../
