include: package:solid_lints/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
    prefer_single_quotes: true
    use_raw_strings: true
